name: catseye
favicon: null
layout_spectrum: 0.93871
typography_spectrum: 0.08708
title: Somewhere On The Spiral
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5f7f7'
    - '#660066'
    - '#7193cf'
    - '#97609f'
    - '#010006'
  brandStrength: 0.5
  lightness: 0.516282677417621
  saturation: 0.125
  rhythmicContrast: 0.2645217082463205
purpose: []
